"""Constants for the VMA Alert integration."""

DOMAIN = "vma_alert_hass"
DEFAULT_POLL_INTERVAL = 10

SCB_GEO_CODES = {
    "00": "Hela Sverige",
    "01": "Stockholms län",
    "03": "Uppsala län",
    "04": "Södermanlands län",
    "05": "Östergötlands län",
    "06": "Jönköpings län",
    "07": "Kronobergs län",
    "08": "Kalmar län",
    "09": "Gotlands län",
    "10": "Blekinge län",
    "12": "Skåne län",
    "13": "Hallands län",
    "14": "Västra Götalands län",
    "17": "Värmlands län",
    "18": "Örebro län",
    "19": "Västmanlands län",
    "20": "Dalarnas län",
    "21": "Gävleborgs län",
    "22": "Västernorrlands län",
    "23": "Jämtlands län",
    "24": "Västerbottens län",
    "25": "Norrbottens län",
    # Municipalities (kommuner) with län prefix and parentheses
    "0114": "(Stockholms län) Upplands Väsby",
    "0115": "(Stockholms län) Vallentuna",
    "0117": "(Stockholms län) Österåker",
    "0120": "(Stockholms län) Värmdö",
    "0123": "(Stockholms län) Järfälla",
    "0125": "(Stockholms län) Ekerö",
    "0126": "(Stockholms län) Huddinge",
    "0127": "(Stockholms län) Botkyrka",
    "0128": "(Stockholms län) Salem",
    "0136": "(Stockholms län) Haninge",
    "0138": "(Stockholms län) Tyresö",
    "0139": "(Stockholms län) Upplands-Bro",
    "0140": "(Stockholms län) Nykvarn",
    "0160": "(Stockholms län) Täby",
    "0162": "(Stockholms län) Danderyd",
    "0163": "(Stockholms län) Sollentuna",
    "0180": "(Stockholms län) Stockholm",
    "0181": "(Stockholms län) Södertälje",
    "0182": "(Stockholms län) Nacka",
    "0183": "(Stockholms län) Sundbyberg",
    "0184": "(Stockholms län) Solna",
    "0186": "(Stockholms län) Lidingö",
    "0187": "(Stockholms län) Vaxholm",
    "0188": "(Stockholms län) Norrtälje",
    "0191": "(Stockholms län) Sigtuna",
    "0192": "(Stockholms län) Nynäshamn",
    "0305": "(Uppsala län) Håbo",
    "0319": "(Uppsala län) Älvkarleby",
    "0330": "(Uppsala län) Knivsta",
    "0331": "(Uppsala län) Heby",
    "0360": "(Uppsala län) Tierp",
    "0380": "(Uppsala län) Uppsala",
    "0381": "(Uppsala län) Enköping",
    "0382": "(Uppsala län) Östhammar",
    "0428": "(Södermanlands län) Vingåker",
    "0461": "(Södermanlands län) Gnesta",
    "0480": "(Södermanlands län) Nyköping",
    "0481": "(Södermanlands län) Oxelösund",
    "0482": "(Södermanlands län) Flen",
    "0483": "(Södermanlands län) Katrineholm",
    "0484": "(Södermanlands län) Eskilstuna",
    "0486": "(Södermanlands län) Strängnäs",
    "0488": "(Södermanlands län) Trosa",
    "0509": "(Östergötlands län) Ödeshög",
    "0512": "(Östergötlands län) Ydre",
    "0513": "(Östergötlands län) Kinda",
    "0560": "(Östergötlands län) Boxholm",
    "0561": "(Östergötlands län) Åtvidaberg",
    "0562": "(Östergötlands län) Finspång",
    "0563": "(Östergötlands län) Valdemarsvik",
    "0580": "(Östergötlands län) Linköping",
    "0581": "(Östergötlands län) Norrköping",
    "0582": "(Östergötlands län) Söderköping",
    "0583": "(Östergötlands län) Motala",
    "0584": "(Östergötlands län) Vadstena",
    "0586": "(Östergötlands län) Mjölby",
    "0604": "(Jönköpings län) Aneby",
    "0617": "(Jönköpings län) Gnosjö",
    "0642": "(Jönköpings län) Mullsjö",
    "0643": "(Jönköpings län) Habo",
    "0662": "(Jönköpings län) Gislaved",
    "0665": "(Jönköpings län) Vaggeryd",
    "0680": "(Jönköpings län) Jönköping",
    "0682": "(Jönköpings län) Nässjö",
    "0683": "(Jönköpings län) Värnamo",
    "0684": "(Jönköpings län) Sävsjö",
    "0685": "(Jönköpings län) Vetlanda",
    "0686": "(Jönköpings län) Eksjö",
    "0687": "(Jönköpings län) Tranås",
    "0760": "(Kronobergs län) Uppvidinge",
    "0761": "(Kronobergs län) Lessebo",
    "0763": "(Kronobergs län) Tingsryd",
    "0764": "(Kronobergs län) Alvesta",
    "0765": "(Kronobergs län) Älmhult",
    "0767": "(Kronobergs län) Markaryd",
    "0780": "(Kronobergs län) Växjö",
    "0781": "(Kronobergs län) Ljungby",
    "0821": "(Kalmar län) Högsby",
    "0834": "(Kalmar län) Torsås",
    "0840": "(Kalmar län) Mörbylånga",
    "0860": "(Kalmar län) Hultsfred",
    "0861": "(Kalmar län) Mönsterås",
    "0862": "(Kalmar län) Emmaboda",
    "0880": "(Kalmar län) Kalmar",
    "0881": "(Kalmar län) Nybro",
    "0882": "(Kalmar län) Oskarshamn",
    "0883": "(Kalmar län) Västervik",
    "0884": "(Kalmar län) Vimmerby",
    "0885": "(Kalmar län) Borgholm",
    "0980": "(Gotlands län) Gotland",
    "1060": "(Blekinge län) Olofström",
    "1080": "(Blekinge län) Karlskrona",
    "1081": "(Blekinge län) Ronneby",
    "1082": "(Blekinge län) Karlshamn",
    "1083": "(Blekinge län) Sölvesborg",
    "1214": "(Skåne län) Svalöv",
    "1230": "(Skåne län) Staffanstorp",
    "1231": "(Skåne län) Burlöv",
    "1233": "(Skåne län) Vellinge",
    "1256": "(Skåne län) Östra Göinge",
    "1257": "(Skåne län) Örkelljunga",
    "1260": "(Skåne län) Bjuv",
    "1261": "(Skåne län) Kävlinge",
    "1262": "(Skåne län) Lomma",
    "1263": "(Skåne län) Svedala",
    "1264": "(Skåne län) Skurup",
    "1265": "(Skåne län) Sjöbo",
    "1266": "(Skåne län) Hörby",
    "1267": "(Skåne län) Höör",
    "1270": "(Skåne län) Tomelilla",
    "1272": "(Skåne län) Bromölla",
    "1273": "(Skåne län) Osby",
    "1275": "(Skåne län) Perstorp",
    "1276": "(Skåne län) Klippan",
    "1277": "(Skåne län) Åstorp",
    "1278": "(Skåne län) Båstad",
    "1280": "(Skåne län) Malmö",
    "1281": "(Skåne län) Lund",
    "1282": "(Skåne län) Landskrona",
    "1283": "(Skåne län) Helsingborg",
    "1284": "(Skåne län) Höganäs",
    "1285": "(Skåne län) Eslöv",
    "1286": "(Skåne län) Ystad",
    "1287": "(Skåne län) Trelleborg",
    "1290": "(Skåne län) Kristianstad",
    "1291": "(Skåne län) Simrishamn",
    "1292": "(Skåne län) Ängelholm",
    "1293": "(Skåne län) Hässleholm",
    "1315": "(Hallands län) Hylte",
    "1380": "(Hallands län) Halmstad",
    "1381": "(Hallands län) Laholm",
    "1382": "(Hallands län) Falkenberg",
    "1383": "(Hallands län) Varberg",
    "1384": "(Hallands län) Kungsbacka",
    "1401": "(Västra Götalands län) Härryda",
    "1402": "(Västra Götalands län) Partille",
    "1407": "(Västra Götalands län) Öckerö",
    "1415": "(Västra Götalands län) Stenungsund",
    "1419": "(Västra Götalands län) Tjörn",
    "1421": "(Västra Götalands län) Orust",
    "1427": "(Västra Götalands län) Sotenäs",
    "1430": "(Västra Götalands län) Munkedal",
    "1435": "(Västra Götalands län) Tanum",
    "1438": "(Västra Götalands län) Dals-Ed",
    "1439": "(Västra Götalands län) Färgelanda",
    "1440": "(Västra Götalands län) Ale",
    "1441": "(Västra Götalands län) Lerum",
    "1442": "(Västra Götalands län) Vårgårda",
    "1443": "(Västra Götalands län) Bollebygd",
    "1444": "(Västra Götalands län) Grästorp",
    "1445": "(Västra Götalands län) Essunga",
    "1446": "(Västra Götalands län) Karlsborg",
    "1447": "(Västra Götalands län) Gullspång",
    "1452": "(Västra Götalands län) Tranemo",
    "1460": "(Västra Götalands län) Bengtsfors",
    "1461": "(Västra Götalands län) Mellerud",
    "1462": "(Västra Götalands län) Lilla Edet",
    "1463": "(Västra Götalands län) Mark",
    "1465": "(Västra Götalands län) Svenljunga",
    "1466": "(Västra Götalands län) Herrljunga",
    "1470": "(Västra Götalands län) Vara",
    "1471": "(Västra Götalands län) Götene",
    "1472": "(Västra Götalands län) Tibro",
    "1473": "(Västra Götalands län) Töreboda",
    "1480": "(Västra Götalands län) Göteborg",
    "1481": "(Västra Götalands län) Mölndal",
    "1482": "(Västra Götalands län) Kungälv",
    "1484": "(Västra Götalands län) Lysekil",
    "1485": "(Västra Götalands län) Uddevalla",
    "1486": "(Västra Götalands län) Strömstad",
    "1487": "(Västra Götalands län) Vänersborg",
    "1488": "(Västra Götalands län) Trollhättan",
    "1489": "(Västra Götalands län) Alingsås",
    "1490": "(Västra Götalands län) Borås",
    "1491": "(Västra Götalands län) Ulricehamn",
    "1492": "(Västra Götalands län) Åmål",
    "1493": "(Västra Götalands län) Mariestad",
    "1494": "(Västra Götalands län) Lidköping",
    "1495": "(Västra Götalands län) Skara",
    "1496": "(Västra Götalands län) Skövde",
    "1497": "(Västra Götalands län) Hjo",
    "1498": "(Västra Götalands län) Tidaholm",
    "1499": "(Västra Götalands län) Falköping",
    "1715": "(Värmlands län) Kil",
    "1730": "(Värmlands län) Eda",
    "1737": "(Värmlands län) Torsby",
    "1760": "(Värmlands län) Storfors",
    "1761": "(Värmlands län) Hammarö",
    "1762": "(Värmlands län) Munkfors",
    "1763": "(Värmlands län) Forshaga",
    "1764": "(Värmlands län) Grums",
    "1765": "(Värmlands län) Årjäng",
    "1766": "(Värmlands län) Sunne",
    "1780": "(Värmlands län) Karlstad",
    "1781": "(Värmlands län) Kristinehamn",
    "1782": "(Värmlands län) Filipstad",
    "1783": "(Värmlands län) Hagfors",
    "1784": "(Värmlands län) Arvika",
    "1785": "(Värmlands län) Säffle",
    "1814": "(Örebro län) Lekeberg",
    "1860": "(Örebro län) Laxå",
    "1861": "(Örebro län) Hallsberg",
    "1862": "(Örebro län) Degerfors",
    "1863": "(Örebro län) Hällefors",
    "1864": "(Örebro län) Ljusnarsberg",
    "1880": "(Örebro län) Örebro",
    "1881": "(Örebro län) Kumla",
    "1882": "(Örebro län) Askersund",
    "1883": "(Örebro län) Karlskoga",
    "1884": "(Örebro län) Nora",
    "1885": "(Örebro län) Lindesberg",
    "1904": "(Västmanlands län) Skinnskatteberg",
    "1907": "(Västmanlands län) Surahammar",
    "1960": "(Västmanlands län) Kungsör",
    "1961": "(Västmanlands län) Hallstahammar",
    "1962": "(Västmanlands län) Norberg",
    "1980": "(Västmanlands län) Västerås",
    "1981": "(Västmanlands län) Sala",
    "1982": "(Västmanlands län) Fagersta",
    "1983": "(Västmanlands län) Köping",
    "1984": "(Västmanlands län) Arboga",
    "2021": "(Dalarnas län) Vansbro",
    "2023": "(Dalarnas län) Malung-Sälen",
    "2026": "(Dalarnas län) Gagnef",
    "2029": "(Dalarnas län) Leksand",
    "2031": "(Dalarnas län) Rättvik",
    "2034": "(Dalarnas län) Orsa",
    "2039": "(Dalarnas län) Älvdalen",
    "2061": "(Dalarnas län) Smedjebacken",
    "2062": "(Dalarnas län) Mora",
    "2080": "(Dalarnas län) Falun",
    "2081": "(Dalarnas län) Borlänge",
    "2082": "(Dalarnas län) Säter",
    "2083": "(Dalarnas län) Hedemora",
    "2084": "(Dalarnas län) Avesta",
    "2085": "(Dalarnas län) Ludvika",
    "2101": "(Gävleborgs län) Ockelbo",
    "2104": "(Gävleborgs län) Hofors",
    "2121": "(Gävleborgs län) Ovanåker",
    "2132": "(Gävleborgs län) Nordanstig",
    "2161": "(Gävleborgs län) Ljusdal",
    "2180": "(Gävleborgs län) Gävle",
    "2181": "(Gävleborgs län) Sandviken",
    "2182": "(Gävleborgs län) Söderhamn",
    "2183": "(Gävleborgs län) Bollnäs",
    "2184": "(Gävleborgs län) Hudiksvall",
    "2260": "(Västernorrlands län) Ånge",
    "2262": "(Västernorrlands län) Timrå",
    "2280": "(Västernorrlands län) Härnösand",
    "2281": "(Västernorrlands län) Sundsvall",
    "2282": "(Västernorrlands län) Kramfors",
    "2283": "(Västernorrlands län) Sollefteå",
    "2284": "(Västernorrlands län) Örnsköldsvik",
    "2303": "(Jämtlands län) Ragunda",
    "2305": "(Jämtlands län) Bräcke",
    "2309": "(Jämtlands län) Krokom",
    "2313": "(Jämtlands län) Strömsund",
    "2321": "(Jämtlands län) Åre",
    "2326": "(Jämtlands län) Berg",
    "2361": "(Jämtlands län) Härjedalen",
    "2380": "(Jämtlands län) Östersund",
    "2401": "(Västerbottens län) Nordmaling",
    "2403": "(Västerbottens län) Bjurholm",
    "2404": "(Västerbottens län) Vindeln",
    "2409": "(Västerbottens län) Robertsfors",
    "2417": "(Västerbottens län) Norsjö",
    "2418": "(Västerbottens län) Malå",
    "2421": "(Västerbottens län) Storuman",
    "2422": "(Västerbottens län) Sorsele",
    "2425": "(Västerbottens län) Dorotea",
    "2460": "(Västerbottens län) Vännäs",
    "2462": "(Västerbottens län) Vilhelmina",
    "2463": "(Västerbottens län) Åsele",
    "2480": "(Västerbottens län) Umeå",
    "2481": "(Västerbottens län) Lycksele",
    "2482": "(Västerbottens län) Skellefteå",
    "2505": "(Norrbottens län) Arvidsjaur",
    "2506": "(Norrbottens län) Arjeplog",
    "2510": "(Norrbottens län) Jokkmokk",
    "2513": "(Norrbottens län) Överkalix",
    "2514": "(Norrbottens län) Kalix",
    "2518": "(Norrbottens län) Övertorneå",
    "2521": "(Norrbottens län) Pajala",
    "2523": "(Norrbottens län) Gällivare",
    "2560": "(Norrbottens län) Älvsbyn",
    "2580": "(Norrbottens län) Luleå",
    "2581": "(Norrbottens län) Piteå",
    "2582": "(Norrbottens län) Boden",
    "2583": "(Norrbottens län) Haparanda",
    "2584": "(Norrbottens län) Kiruna"
}